# Generated by Django 3.0.3 on 2020-08-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfAllBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=50)),
                ('published_date', models.CharField(max_length=4)),
                ('categories', models.CharField(max_length=50)),
                ('average_rating', models.IntegerField()),
                ('rating_counts', models.IntegerField()),
                ('thumbnail', models.URLField()),
            ],
        ),
    ]
